version: "20.10"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "shakespeare"
      MYSQL_USER: "foobar"
      MYSQL_PASSWORD: "1234"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - "33061:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init-scripts/oss-db-full.sql:/docker-entrypoint-initdb.d/oss-db-full.sql
volumes:
  db_data:
